services:
     oc_platform.antispam:
         class: OC\PlatformBundle\Antispam\OCAntispam
         arguments: [@mailer, %locale%, 50]
     oc_platform.doctrine.notification:
        class: OC\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
     form.type.datePicker:
        class: OC\PlatformBundle\Form\Type\DatePickerType
        tags:
            - { name: form.type, alias: datePicker }