<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
    public function getApplicationsWithAdvert($limit){
		
	  $qb = $this->createQueryBuilder('app');
	
	  $qb
        ->join('app.advert', 'adv')
        ->addSelect('adv')
      ;
	
      $qb->setMaxResults($limit);
      
	  return $qb
	    ->getQuery()
	    ->getResult()
	  ;
	  
    }
    
    public function isFlood($ip, $time){
        
        return false;
    }
}